{erl_opts, Opts} = lists:keyfind(erl_opts, 1, CONFIG),
NewOpts =
    case os:type() of
        {unix,linux} ->
            [native, {d, linux}]++Opts;
        _ ->
            [{d, windows}]++Opts
    end,
lists:keyreplace(erl_opts, 1, CONFIG, {erl_opts, [
    {d, process_call_mod, player_server},

    {d, dev},
%%    {d, prod},

    {d, db_node, 'db@192.168.2.21'},
    {d, mgr_node, 'mgr@192.168.2.21'},
    {d, push_node, 'push@192.168.2.21'}
    IsDebug|NewOpts]}).